(rocq.extraction
 (prelude extraction)
 (extracted_files pipeline.ml pipeline.mli)
 (theories Wasm Stdlib Wasmopt mathcomp compcert ExtLib Flocq HB parseque elpi elpi_elpi))

(executables
 (names main main_timed)
 (public_names wasm-opt-cert -)
 (package rocq-wasm-opt-cert)
 (flags :standard -w -a)
 (libraries unix)
 (modules main main_timed pipeline))
